<?php
/**
 * Domus Desk REST API v1 — the route table, extracted so both the front
 * controller (index.php) and the OpenAPI generator (lib/openapi.php) read one
 * authoritative list. [method, pattern, [resource, action] | null, handler].
 */
return [
    ['GET',    '#^/$#',                                    null,                              'apiHandleRoot'],
    ['GET',    '#^/ping$#',                                null,                              'apiHandlePing'],

    ['GET',    '#^/tickets$#',                             ['tickets', 'read'],               'apiTicketsList'],
    ['POST',   '#^/tickets$#',                             ['tickets', 'create'],             'apiTicketsCreate'],
    ['GET',    '#^/tickets/(\d+)$#',                       ['tickets', 'read'],               'apiTicketsGet'],
    ['PATCH',  '#^/tickets/(\d+)$#',                       ['tickets', 'update'],             'apiTicketsUpdate'],
    ['DELETE', '#^/tickets/(\d+)$#',                       ['tickets', 'delete'],             'apiTicketsDelete'],
    ['POST',   '#^/tickets/(\d+)/restore$#',               ['tickets', 'restore'],            'apiTicketsRestore'],

    ['GET',    '#^/tickets/(\d+)/notes$#',                 ['ticket_notes', 'read'],          'apiTicketNotesList'],
    ['POST',   '#^/tickets/(\d+)/notes$#',                 ['ticket_notes', 'create'],        'apiTicketNotesCreate'],
    ['GET',    '#^/tickets/(\d+)/thread$#',                ['ticket_thread', 'read'],         'apiTicketThreadList'],
    ['GET',    '#^/tickets/(\d+)/audit$#',                 ['ticket_audit', 'read'],          'apiTicketAuditList'],
    ['GET',    '#^/tickets/(\d+)/sla$#',                   ['ticket_sla', 'read'],            'apiTicketSlaGet'],
    ['GET',    '#^/tickets/(\d+)/time-entries$#',          ['ticket_time_entries', 'read'],   'apiTicketTimeEntriesList'],
    ['POST',   '#^/tickets/(\d+)/time-entries$#',          ['ticket_time_entries', 'create'], 'apiTicketTimeEntriesCreate'],
    ['DELETE', '#^/tickets/(\d+)/time-entries/(\d+)$#',    ['ticket_time_entries', 'delete'], 'apiTicketTimeEntriesDelete'],

    ['GET',    '#^/assets$#',                              ['assets', 'read'],                'apiAssetsList'],
    ['POST',   '#^/assets$#',                              ['assets', 'create'],              'apiAssetsCreate'],
    ['GET',    '#^/assets/(\d+)$#',                        ['assets', 'read'],                'apiAssetsGet'],
    ['PATCH',  '#^/assets/(\d+)$#',                        ['assets', 'update'],              'apiAssetsUpdate'],
    ['GET',    '#^/assets/(\d+)/assignments$#',            ['asset_assignments', 'read'],     'apiAssetAssignmentsList'],
    ['POST',   '#^/assets/(\d+)/assignments$#',            ['asset_assignments', 'create'],   'apiAssetAssignmentsCreate'],
    ['DELETE', '#^/assets/(\d+)/assignments/(\d+)$#',      ['asset_assignments', 'delete'],   'apiAssetAssignmentsDelete'],
    ['GET',    '#^/assets/(\d+)/history$#',                ['asset_history', 'read'],         'apiAssetHistoryList'],
    ['GET',    '#^/assets/(\d+)/custody$#',                ['asset_history', 'read'],         'apiAssetCustodyList'],
    ['GET',    '#^/assets/(\d+)/disks$#',                  ['asset_inventory', 'read'],       'apiAssetDisksList'],
    ['GET',    '#^/assets/(\d+)/network-adapters$#',       ['asset_inventory', 'read'],       'apiAssetNetworkAdaptersList'],
    ['GET',    '#^/assets/(\d+)/devices$#',                ['asset_inventory', 'read'],       'apiAssetDevicesList'],
    ['GET',    '#^/assets/(\d+)/software$#',               ['asset_inventory', 'read'],       'apiAssetSoftwareList'],
    ['GET',    '#^/asset-types$#',                         ['reference', 'read'],             'apiAssetTypesList'],
    ['GET',    '#^/asset-statuses$#',                      ['reference', 'read'],             'apiAssetStatusesList'],
    ['GET',    '#^/asset-locations$#',                     ['reference', 'read'],             'apiAssetLocationsList'],
    ['GET',    '#^/suppliers$#',                           ['reference', 'read'],             'apiSuppliersList'],

    ['GET',    '#^/problems$#',                            ['problems', 'read'],              'apiProblemsList'],
    ['POST',   '#^/problems$#',                            ['problems', 'create'],            'apiProblemsCreate'],
    ['GET',    '#^/problems/(\d+)$#',                      ['problems', 'read'],              'apiProblemsGet'],
    ['PATCH',  '#^/problems/(\d+)$#',                      ['problems', 'update'],            'apiProblemsUpdate'],
    ['DELETE', '#^/problems/(\d+)$#',                      ['problems', 'delete'],            'apiProblemsDelete'],
    ['GET',    '#^/problems/(\d+)/notes$#',                ['problem_notes', 'read'],         'apiProblemNotesList'],
    ['POST',   '#^/problems/(\d+)/notes$#',                ['problem_notes', 'create'],       'apiProblemNotesCreate'],
    ['GET',    '#^/problems/(\d+)/audit$#',                ['problem_audit', 'read'],         'apiProblemAuditList'],
    ['POST',   '#^/problems/(\d+)/tickets$#',              ['problem_links', 'create'],       'apiProblemTicketsLink'],
    ['DELETE', '#^/problems/(\d+)/tickets/(\d+)$#',        ['problem_links', 'delete'],       'apiProblemTicketsUnlink'],
    ['POST',   '#^/problems/(\d+)/changes$#',              ['problem_links', 'create'],       'apiProblemChangesLink'],
    ['DELETE', '#^/problems/(\d+)/changes/(\d+)$#',        ['problem_links', 'delete'],       'apiProblemChangesUnlink'],
    ['GET',    '#^/problem-statuses$#',                    ['reference', 'read'],             'apiProblemStatusesList'],
    ['GET',    '#^/problem-priorities$#',                  ['reference', 'read'],             'apiProblemPrioritiesList'],

    ['GET',    '#^/changes$#',                             ['changes', 'read'],               'apiChangesList'],
    ['POST',   '#^/changes$#',                             ['changes', 'create'],             'apiChangesCreate'],
    ['GET',    '#^/changes/(\d+)$#',                       ['changes', 'read'],               'apiChangesGet'],
    ['PATCH',  '#^/changes/(\d+)$#',                       ['changes', 'update'],             'apiChangesUpdate'],
    ['DELETE', '#^/changes/(\d+)$#',                       ['changes', 'delete'],             'apiChangesDelete'],
    ['GET',    '#^/changes/(\d+)/comments$#',              ['change_comments', 'read'],       'apiChangeCommentsList'],
    ['POST',   '#^/changes/(\d+)/comments$#',              ['change_comments', 'create'],     'apiChangeCommentsCreate'],
    ['DELETE', '#^/changes/(\d+)/comments/(\d+)$#',        ['change_comments', 'delete'],     'apiChangeCommentsDelete'],
    ['GET',    '#^/changes/(\d+)/audit$#',                 ['change_audit', 'read'],          'apiChangeAuditList'],
    ['GET',    '#^/changes/(\d+)/cab$#',                   ['change_cab', 'read'],            'apiChangeCabGet'],
    ['POST',   '#^/changes/(\d+)/cab$#',                   ['change_cab', 'manage'],          'apiChangeCabSave'],
    ['POST',   '#^/changes/(\d+)/cab/vote$#',              ['change_cab', 'vote'],            'apiChangeCabVote'],
    ['GET',    '#^/change-statuses$#',                     ['reference', 'read'],             'apiChangeStatusesList'],
    ['GET',    '#^/change-types$#',                        ['reference', 'read'],             'apiChangeTypesList'],
    ['GET',    '#^/change-priorities$#',                   ['reference', 'read'],             'apiChangePrioritiesList'],
    ['GET',    '#^/change-impacts$#',                      ['reference', 'read'],             'apiChangeImpactsList'],
    ['GET',    '#^/change-categories$#',                   ['reference', 'read'],             'apiChangeCategoriesList'],

    ['GET',    '#^/knowledge/articles$#',                  ['knowledge', 'read'],             'apiKnowledgeArticlesList'],
    ['POST',   '#^/knowledge/articles$#',                  ['knowledge', 'create'],           'apiKnowledgeArticlesCreate'],
    ['GET',    '#^/knowledge/articles/(\d+)$#',            ['knowledge', 'read'],             'apiKnowledgeArticlesGet'],
    ['PATCH',  '#^/knowledge/articles/(\d+)$#',            ['knowledge', 'update'],           'apiKnowledgeArticlesUpdate'],
    ['DELETE', '#^/knowledge/articles/(\d+)$#',            ['knowledge', 'delete'],           'apiKnowledgeArticlesDelete'],
    ['POST',   '#^/knowledge/articles/(\d+)/restore$#',    ['knowledge', 'restore'],          'apiKnowledgeArticlesRestore'],
    ['DELETE', '#^/knowledge/articles/(\d+)/permanent$#',  ['knowledge', 'purge'],            'apiKnowledgeArticlesPurge'],
    ['GET',    '#^/knowledge/articles/(\d+)/versions$#',   ['knowledge_versions', 'read'],    'apiKnowledgeVersionsList'],
    ['GET',    '#^/knowledge/articles/(\d+)/versions/(\d+)$#', ['knowledge_versions', 'read'], 'apiKnowledgeVersionsGet'],
    ['GET',    '#^/knowledge/tags$#',                      ['reference', 'read'],             'apiKnowledgeTagsList'],

    ['GET',    '#^/tasks$#',                               ['tasks', 'read'],                 'apiTasksList'],
    ['POST',   '#^/tasks$#',                               ['tasks', 'create'],               'apiTasksCreate'],
    ['GET',    '#^/tasks/(\d+)$#',                         ['tasks', 'read'],                 'apiTasksGet'],
    ['PATCH',  '#^/tasks/(\d+)$#',                         ['tasks', 'update'],               'apiTasksUpdate'],
    ['DELETE', '#^/tasks/(\d+)$#',                         ['tasks', 'delete'],               'apiTasksDelete'],
    ['POST',   '#^/tasks/(\d+)/move$#',                    ['tasks', 'update'],               'apiTasksMove'],
    ['GET',    '#^/tasks/(\d+)/comments$#',                ['task_comments', 'read'],         'apiTaskCommentsList'],
    ['POST',   '#^/tasks/(\d+)/comments$#',                ['task_comments', 'create'],       'apiTaskCommentsCreate'],
    ['GET',    '#^/task-statuses$#',                       ['reference', 'read'],             'apiTaskStatusesList'],
    ['GET',    '#^/task-priorities$#',                     ['reference', 'read'],             'apiTaskPrioritiesList'],
    ['GET',    '#^/task-tags$#',                           ['reference', 'read'],             'apiTaskTagsList'],

    ['GET',    '#^/cmdb/classes$#',                        ['cmdb_classes', 'read'],          'apiCmdbClassesList'],
    ['GET',    '#^/cmdb/classes/(\d+)$#',                  ['cmdb_classes', 'read'],          'apiCmdbClassesGet'],
    ['GET',    '#^/cmdb/objects$#',                        ['cmdb_objects', 'read'],          'apiCmdbObjectsList'],
    ['POST',   '#^/cmdb/objects$#',                        ['cmdb_objects', 'create'],        'apiCmdbObjectsCreate'],
    ['GET',    '#^/cmdb/objects/(\d+)$#',                  ['cmdb_objects', 'read'],          'apiCmdbObjectsGet'],
    ['PATCH',  '#^/cmdb/objects/(\d+)$#',                  ['cmdb_objects', 'update'],        'apiCmdbObjectsUpdate'],
    ['DELETE', '#^/cmdb/objects/(\d+)$#',                  ['cmdb_objects', 'delete'],        'apiCmdbObjectsDelete'],
    ['GET',    '#^/cmdb/objects/(\d+)/impact$#',           ['cmdb_objects', 'read'],          'apiCmdbObjectImpact'],
    ['POST',   '#^/cmdb/objects/(\d+)/relationships$#',    ['cmdb_relationships', 'create'],  'apiCmdbRelationshipsCreate'],
    ['DELETE', '#^/cmdb/objects/(\d+)/relationships/(\d+)$#', ['cmdb_relationships', 'delete'], 'apiCmdbRelationshipsDelete'],
    ['GET',    '#^/cmdb/objects/(\d+)/tickets$#',          ['cmdb_ticket_links', 'read'],     'apiCmdbObjectTicketsList'],
    ['POST',   '#^/cmdb/objects/(\d+)/tickets$#',          ['cmdb_ticket_links', 'create'],   'apiCmdbObjectTicketsLink'],
    ['DELETE', '#^/cmdb/objects/(\d+)/tickets/(\d+)$#',    ['cmdb_ticket_links', 'delete'],   'apiCmdbObjectTicketsUnlink'],
    ['GET',    '#^/cmdb-relationship-types$#',             ['reference', 'read'],             'apiCmdbRelationshipTypesList'],

    ['GET',    '#^/contracts$#',                           ['contracts', 'read'],             'apiContractsList'],
    ['POST',   '#^/contracts$#',                           ['contracts', 'create'],           'apiContractsCreate'],
    ['GET',    '#^/contracts/(\d+)$#',                     ['contracts', 'read'],             'apiContractsGet'],
    ['PATCH',  '#^/contracts/(\d+)$#',                     ['contracts', 'update'],           'apiContractsUpdate'],
    ['DELETE', '#^/contracts/(\d+)$#',                     ['contracts', 'delete'],           'apiContractsDelete'],
    ['GET',    '#^/contracts/(\d+)/terms$#',               ['contract_terms', 'read'],        'apiContractTermsGet'],
    ['POST',   '#^/contracts/(\d+)/terms$#',               ['contract_terms', 'update'],      'apiContractTermsSave'],
    ['POST',   '#^/suppliers$#',                           ['suppliers', 'create'],           'apiSuppliersCreate'],
    ['GET',    '#^/suppliers/(\d+)$#',                     ['suppliers', 'read'],             'apiSuppliersGet'],
    ['PATCH',  '#^/suppliers/(\d+)$#',                     ['suppliers', 'update'],           'apiSuppliersUpdate'],
    ['DELETE', '#^/suppliers/(\d+)$#',                     ['suppliers', 'delete'],           'apiSuppliersDelete'],
    ['GET',    '#^/suppliers/(\d+)/contacts$#',            ['supplier_contacts', 'read'],     'apiSupplierContactsList'],
    ['POST',   '#^/suppliers/(\d+)/contacts$#',            ['supplier_contacts', 'create'],   'apiSupplierContactsCreate'],
    ['PATCH',  '#^/suppliers/(\d+)/contacts/(\d+)$#',      ['supplier_contacts', 'update'],   'apiSupplierContactsUpdate'],
    ['DELETE', '#^/suppliers/(\d+)/contacts/(\d+)$#',      ['supplier_contacts', 'delete'],   'apiSupplierContactsDelete'],
    ['GET',    '#^/contract-statuses$#',                   ['reference', 'read'],             'apiContractStatusesList'],
    ['GET',    '#^/payment-schedules$#',                   ['reference', 'read'],             'apiPaymentSchedulesList'],
    ['GET',    '#^/supplier-types$#',                      ['reference', 'read'],             'apiSupplierTypesList'],
    ['GET',    '#^/supplier-statuses$#',                   ['reference', 'read'],             'apiSupplierStatusesList'],
    ['GET',    '#^/contract-term-tabs$#',                  ['reference', 'read'],             'apiContractTermTabsList'],

    ['GET',    '#^/calendar/events$#',                     ['calendar_events', 'read'],       'apiCalendarEventsList'],
    ['POST',   '#^/calendar/events$#',                     ['calendar_events', 'create'],     'apiCalendarEventsCreate'],
    ['GET',    '#^/calendar/events/(\d+)$#',               ['calendar_events', 'read'],       'apiCalendarEventsGet'],
    ['PATCH',  '#^/calendar/events/(\d+)$#',               ['calendar_events', 'update'],     'apiCalendarEventsUpdate'],
    ['DELETE', '#^/calendar/events/(\d+)$#',               ['calendar_events', 'delete'],     'apiCalendarEventsDelete'],
    ['GET',    '#^/calendar-categories$#',                 ['reference', 'read'],             'apiCalendarCategoriesList'],

    ['GET',    '#^/software/apps$#',                       ['software_inventory', 'read'],    'apiSoftwareAppsList'],
    ['GET',    '#^/software/apps/(\d+)$#',                 ['software_inventory', 'read'],    'apiSoftwareAppsGet'],
    ['GET',    '#^/software/apps/(\d+)/machines$#',        ['software_inventory', 'read'],    'apiSoftwareAppMachinesList'],
    ['GET',    '#^/software/licences$#',                   ['software_licences', 'read'],     'apiSoftwareLicencesList'],
    ['POST',   '#^/software/licences$#',                   ['software_licences', 'create'],   'apiSoftwareLicencesCreate'],
    ['GET',    '#^/software/licences/(\d+)$#',             ['software_licences', 'read'],     'apiSoftwareLicencesGet'],
    ['PATCH',  '#^/software/licences/(\d+)$#',             ['software_licences', 'update'],   'apiSoftwareLicencesUpdate'],
    ['DELETE', '#^/software/licences/(\d+)$#',             ['software_licences', 'delete'],   'apiSoftwareLicencesDelete'],

    ['GET',    '#^/service-status/services$#',             ['services', 'read'],              'apiStatusServicesList'],
    ['POST',   '#^/service-status/services$#',             ['services', 'create'],            'apiStatusServicesCreate'],
    ['GET',    '#^/service-status/services/(\d+)$#',       ['services', 'read'],              'apiStatusServicesGet'],
    ['PATCH',  '#^/service-status/services/(\d+)$#',       ['services', 'update'],            'apiStatusServicesUpdate'],
    ['DELETE', '#^/service-status/services/(\d+)$#',       ['services', 'delete'],            'apiStatusServicesDelete'],
    ['GET',    '#^/service-status/incidents$#',            ['service_incidents', 'read'],     'apiStatusIncidentsList'],
    ['POST',   '#^/service-status/incidents$#',            ['service_incidents', 'create'],   'apiStatusIncidentsCreate'],
    ['GET',    '#^/service-status/incidents/(\d+)$#',      ['service_incidents', 'read'],     'apiStatusIncidentsGet'],
    ['PATCH',  '#^/service-status/incidents/(\d+)$#',      ['service_incidents', 'update'],   'apiStatusIncidentsUpdate'],
    ['DELETE', '#^/service-status/incidents/(\d+)$#',      ['service_incidents', 'delete'],   'apiStatusIncidentsDelete'],
    ['GET',    '#^/service-incident-statuses$#',           ['reference', 'read'],             'apiServiceIncidentStatusesList'],
    ['GET',    '#^/service-impact-levels$#',               ['reference', 'read'],             'apiServiceImpactLevelsList'],

    ['GET',    '#^/morning-checks/checks$#',               ['morning_checks', 'read'],        'apiMorningChecksList'],
    ['POST',   '#^/morning-checks/checks$#',               ['morning_checks', 'create'],      'apiMorningChecksCreate'],
    ['GET',    '#^/morning-checks/checks/(\d+)$#',         ['morning_checks', 'read'],        'apiMorningChecksGet'],
    ['PATCH',  '#^/morning-checks/checks/(\d+)$#',         ['morning_checks', 'update'],      'apiMorningChecksUpdate'],
    ['DELETE', '#^/morning-checks/checks/(\d+)$#',         ['morning_checks', 'delete'],      'apiMorningChecksDelete'],
    ['GET',    '#^/morning-checks/board$#',                ['morning_check_results', 'read'], 'apiMorningChecksBoard'],
    ['GET',    '#^/morning-checks/results$#',              ['morning_check_results', 'read'], 'apiMorningCheckResultsList'],
    ['GET',    '#^/morning-checks/results/(\d+)$#',        ['morning_check_results', 'read'], 'apiMorningCheckResultsGet'],
    ['POST',   '#^/morning-checks/results$#',              ['morning_check_results', 'record'], 'apiMorningCheckResultsRecord'],
    ['GET',    '#^/morning-check-statuses$#',              ['reference', 'read'],             'apiMorningCheckStatusesList'],

    ['GET',    '#^/forms$#',                               ['forms', 'read'],                 'apiFormsList'],
    ['POST',   '#^/forms$#',                               ['forms', 'create'],               'apiFormsCreate'],
    ['GET',    '#^/forms/(\d+)$#',                         ['forms', 'read'],                 'apiFormsGet'],
    ['PATCH',  '#^/forms/(\d+)$#',                         ['forms', 'update'],               'apiFormsUpdate'],
    ['DELETE', '#^/forms/(\d+)$#',                         ['forms', 'delete'],               'apiFormsDelete'],
    ['GET',    '#^/forms/(\d+)/versions$#',                ['forms', 'read'],                 'apiFormVersionsList'],
    ['POST',   '#^/forms/(\d+)/versions$#',                ['forms', 'create'],               'apiFormVersionsCreate'],
    ['GET',    '#^/forms/(\d+)/submissions$#',             ['form_submissions', 'read'],      'apiFormSubmissionsList'],
    ['POST',   '#^/forms/(\d+)/submissions$#',             ['form_submissions', 'create'],    'apiFormSubmissionsCreate'],
    ['GET',    '#^/forms/(\d+)/submissions/(\d+)$#',       ['form_submissions', 'read'],      'apiFormSubmissionsGet'],
    ['DELETE', '#^/forms/(\d+)/submissions/(\d+)$#',       ['form_submissions', 'delete'],    'apiFormSubmissionsDelete'],

    ['GET',    '#^/workflows$#',                           ['workflows', 'read'],             'apiWorkflowsList'],
    ['POST',   '#^/workflows$#',                           ['workflows', 'create'],           'apiWorkflowsCreate'],
    ['GET',    '#^/workflows/(\d+)$#',                     ['workflows', 'read'],             'apiWorkflowsGet'],
    ['PATCH',  '#^/workflows/(\d+)$#',                     ['workflows', 'update'],           'apiWorkflowsUpdate'],
    ['DELETE', '#^/workflows/(\d+)$#',                     ['workflows', 'delete'],           'apiWorkflowsDelete'],
    ['POST',   '#^/workflows/(\d+)/fire$#',                ['workflows', 'fire'],             'apiWorkflowsFire'],
    ['GET',    '#^/workflows/(\d+)/executions$#',          ['workflow_executions', 'read'],   'apiWorkflowExecutionsList'],
    ['GET',    '#^/workflow-executions$#',                 ['workflow_executions', 'read'],   'apiWorkflowExecutionsListAll'],
    ['GET',    '#^/workflow-executions/(\d+)$#',           ['workflow_executions', 'read'],   'apiWorkflowExecutionsGet'],
    ['GET',    '#^/workflow-triggers$#',                   ['reference', 'read'],             'apiWorkflowTriggersList'],
    ['GET',    '#^/workflow-actions$#',                    ['reference', 'read'],             'apiWorkflowActionsList'],

    ['GET',    '#^/network-diagrams$#',                        ['network_diagrams', 'read'],   'apiNmDiagramsList'],
    ['POST',   '#^/network-diagrams$#',                        ['network_diagrams', 'create'], 'apiNmDiagramsCreate'],
    ['GET',    '#^/network-diagrams/(\d+)$#',                  ['network_diagrams', 'read'],   'apiNmDiagramsGet'],
    ['PATCH',  '#^/network-diagrams/(\d+)$#',                  ['network_diagrams', 'update'], 'apiNmDiagramsUpdate'],
    ['DELETE', '#^/network-diagrams/(\d+)$#',                  ['network_diagrams', 'delete'], 'apiNmDiagramsDelete'],
    ['GET',    '#^/network-diagrams/(\d+)/versions$#',         ['network_diagrams', 'read'],   'apiNmVersionsList'],
    ['POST',   '#^/network-diagrams/(\d+)/versions$#',         ['network_diagrams', 'create'], 'apiNmVersionsCreate'],
    ['GET',    '#^/network-diagrams/(\d+)/suggestions$#',      ['network_diagrams', 'read'],   'apiNmSuggestionsList'],
    ['POST',   '#^/network-diagrams/(\d+)/nodes$#',            ['network_diagrams', 'update'], 'apiNmNodesCreate'],
    ['PATCH',  '#^/network-diagrams/(\d+)/nodes/(\d+)$#',      ['network_diagrams', 'update'], 'apiNmNodesUpdate'],
    ['DELETE', '#^/network-diagrams/(\d+)/nodes/(\d+)$#',      ['network_diagrams', 'update'], 'apiNmNodesDelete'],
    ['POST',   '#^/network-diagrams/(\d+)/connectors$#',       ['network_diagrams', 'update'], 'apiNmConnectorsCreate'],
    ['PATCH',  '#^/network-diagrams/(\d+)/connectors/(\d+)$#', ['network_diagrams', 'update'], 'apiNmConnectorsUpdate'],
    ['DELETE', '#^/network-diagrams/(\d+)/connectors/(\d+)$#', ['network_diagrams', 'update'], 'apiNmConnectorsDelete'],
    ['GET',    '#^/cmdb-icons$#',                              ['reference', 'read'],          'apiCmdbIconsList'],

    ['GET',    '#^/users$#',                               ['users', 'read'],                 'apiUsersList'],
    ['POST',   '#^/users$#',                               ['users', 'create'],               'apiUsersCreate'],
    ['GET',    '#^/users/(\d+)$#',                         ['users', 'read'],                 'apiUsersGet'],
    ['PATCH',  '#^/users/(\d+)$#',                         ['users', 'update'],               'apiUsersUpdate'],

    ['GET',    '#^/analysts$#',                            ['analysts', 'read'],              'apiAnalystsList'],
    ['GET',    '#^/companies$#',                           ['companies', 'read'],             'apiCompaniesList'],
    ['GET',    '#^/statuses$#',                            ['reference', 'read'],             'apiStatusesList'],
    ['GET',    '#^/priorities$#',                          ['reference', 'read'],             'apiPrioritiesList'],
    ['GET',    '#^/ticket-types$#',                        ['reference', 'read'],             'apiTicketTypesList'],
    ['GET',    '#^/origins$#',                             ['reference', 'read'],             'apiOriginsList'],
    ['GET',    '#^/departments$#',                         ['reference', 'read'],             'apiDepartmentsList'],
];
