<?php
/**
 * Debug Tool D001 — Demo Core Data Import
 *
 * Captures everything we might want to know when a user reports that clicking
 * "Import Core Data" on the Demo Data screen doesn't work. Designed to be run
 * once and emailed back — assumes nothing about the surrounding code, so it
 * works even if the import script, JSON file, config, DB or schema is broken.
 *
 * Output: plain text, section-delimited with === HEADERS === for easy skimming.
 */

// Run without halting on individual errors — the diagnostic itself must never
// crash. Errors get captured into sections and reported.
@session_start();

$DIAG_ID   = 'D001';
$DIAG_NAME = 'Demo Core Data Import';

// ---- helpers -----------------------------------------------------------

$sections = [];
function addSection(&$sections, $title, $body) {
    if (is_array($body)) $body = implode("\n", $body);
    $sections[] = "=== {$title} ===\n" . rtrim($body, "\n");
}
function bool_str($v) { return $v ? 'YES' : 'NO'; }
function safe_size($path) {
    if (!file_exists($path)) return 'n/a';
    $sz = @filesize($path);
    return $sz === false ? 'unknown' : ($sz . ' bytes');
}
function redact_row($row, $redactCols = ['password_hash', 'totp_secret', 'username', 'email', 'full_name', 'display_name', 'preferred_name']) {
    if (!is_array($row)) return $row;
    foreach ($redactCols as $c) {
        if (array_key_exists($c, $row) && $row[$c] !== null && $row[$c] !== '') {
            $row[$c] = '[redacted ' . strlen((string)$row[$c]) . ' chars]';
        }
    }
    return $row;
}

// Expected columns for the 9 tables the core import touches. Carried here
// deliberately so D001 does not depend on db_verify.php being present/parseable.
$EXPECTED_COLUMNS = [
    'analysts'          => ['id','username','password_hash','full_name','email','is_active','created_datetime','last_login_datetime','last_modified_datetime','totp_secret','totp_enabled','trust_device_enabled','password_changed_datetime','failed_login_count','locked_until'],
    'users'             => ['id','email','display_name','preferred_name','password_hash','totp_secret','totp_enabled','created_at'],
    'departments'       => ['id','name','description','is_active','display_order','created_datetime'],
    'teams'             => ['id','name','description','display_order','is_active','created_datetime','updated_datetime'],
    'analyst_teams'     => ['id','analyst_id','team_id','created_datetime'],
    'department_teams'  => ['id','department_id','team_id','created_datetime'],
    'ticket_types'      => ['id','name','description','is_active','display_order','created_datetime'],
    'ticket_origins'    => ['id','name','description','display_order','is_active','created_datetime'],
    'ticket_prefixes'   => ['id','prefix','description','department_id','is_default'],
];

// ---- 1. HEADER ---------------------------------------------------------

$now = gmdate('Y-m-d H:i:s') . ' UTC';
addSection($sections, "REPORT HEADER", [
    "Diagnostic     : {$DIAG_ID} — {$DIAG_NAME}",
    "Generated      : {$now}",
    "Generated by   : analyst_id=" . ($_SESSION['analyst_id'] ?? '(not logged in)'),
    "Server time TZ : " . date_default_timezone_get(),
    "Send this entire report back to support so we can diagnose what failed.",
]);

// ---- 2. AUTH GATE ------------------------------------------------------

if (!isset($_SESSION['analyst_id'])) {
    addSection($sections, "AUTH", "FAIL: not logged in. Log into Domus Desk in the same browser, then re-run this diagnostic.");
    header('Content-Type: text/plain; charset=utf-8');
    echo implode("\n\n", $sections) . "\n";
    exit;
}

// ---- 3. ENVIRONMENT ----------------------------------------------------

$env = [];
$env[] = "PHP version    : " . PHP_VERSION;
$env[] = "OS             : " . PHP_OS . " — " . php_uname('s') . ' ' . php_uname('r');
$env[] = "Server SAPI    : " . PHP_SAPI;
$env[] = "Server software: " . ($_SERVER['SERVER_SOFTWARE'] ?? 'unknown');
$env[] = "Document root  : " . ($_SERVER['DOCUMENT_ROOT'] ?? 'unknown');
$env[] = "Script path    : " . __FILE__;
$env[] = "";
$wantExt = ['pdo', 'pdo_mysql', 'json', 'mbstring', 'openssl', 'session'];
foreach ($wantExt as $e) {
    $env[] = "ext:{$e}".str_repeat(' ', max(0, 11 - strlen($e))) . " : " . bool_str(extension_loaded($e));
}
$env[] = "";
$env[] = "memory_limit       : " . ini_get('memory_limit');
$env[] = "max_execution_time : " . ini_get('max_execution_time') . 's';
$env[] = "post_max_size      : " . ini_get('post_max_size');
$env[] = "upload_max_filesize: " . ini_get('upload_max_filesize');
$env[] = "display_errors     : " . ini_get('display_errors');
$env[] = "error_reporting    : " . ini_get('error_reporting');
addSection($sections, "ENVIRONMENT", $env);

// ---- 4. CONFIG FILES ---------------------------------------------------

$cfg = [];
$rootCfg = realpath(__DIR__ . '/../../../config.php');
$cfg[] = "config.php path resolved: " . ($rootCfg ?: '(not resolved)');
$cfg[] = "config.php exists       : " . bool_str($rootCfg && file_exists($rootCfg));
$cfg[] = "config.php size         : " . ($rootCfg ? safe_size($rootCfg) : 'n/a');

// Find the $db_config_path declared in config.php without including it (so we
// don't crash if it fatals or echoes — we'll try a clean include further down).
$db_config_path = null;
if ($rootCfg && is_readable($rootCfg)) {
    $cfgSrc = @file_get_contents($rootCfg);
    if ($cfgSrc !== false && preg_match('/\$db_config_path\s*=\s*[\'"](.+?)[\'"]\s*;/', $cfgSrc, $m)) {
        $db_config_path = $m[1];
    }
}
$cfg[] = "";
$cfg[] = "db_config_path (parsed) : " . ($db_config_path ?: '(not found in config.php — expected pattern: $db_config_path = "...";)');
if ($db_config_path) {
    $cfg[] = "db_config file exists   : " . bool_str(file_exists($db_config_path));
    $cfg[] = "db_config file readable : " . bool_str(is_readable($db_config_path));
    $cfg[] = "db_config size          : " . safe_size($db_config_path);
}

// Try to include config and report what we get. require_once is idempotent,
// so calling it again does nothing harmful.
$cfg[] = "";
$includeOk = false;
try {
    if ($rootCfg) {
        @require_once $rootCfg;
        $includeOk = true;
    }
} catch (Throwable $e) {
    $cfg[] = "config.php include      : FAILED — " . $e->getMessage();
}

// Debug tools are administrators-only (issue #34). Fail closed.
require_once __DIR__ . '/../../../includes/functions.php';
try { $__dbgAdmin = !empty($_SESSION['analyst_id']) && analystIsAdmin(connectToDatabase(), (int)$_SESSION['analyst_id']); } catch (Throwable $e) { $__dbgAdmin = false; }
if (!$__dbgAdmin) { http_response_code(403); if (!headers_sent()) header('Content-Type: text/plain; charset=utf-8'); echo "Administrator access required.\n"; exit; }

$cfg[] = "config.php include      : " . ($includeOk ? 'OK' : 'NOT ATTEMPTED');
$cfg[] = "DB_SERVER defined       : " . bool_str(defined('DB_SERVER'))   . (defined('DB_SERVER')   ? ' = ' . DB_SERVER : '');
$cfg[] = "DB_NAME defined         : " . bool_str(defined('DB_NAME'))     . (defined('DB_NAME')     ? ' = ' . DB_NAME : '');
$cfg[] = "DB_USERNAME defined     : " . bool_str(defined('DB_USERNAME')) . (defined('DB_USERNAME') ? ' (value redacted, length=' . strlen(DB_USERNAME) . ')' : '');
$cfg[] = "DB_PASSWORD defined     : " . bool_str(defined('DB_PASSWORD')) . (defined('DB_PASSWORD') ? ' (value redacted, length=' . strlen(DB_PASSWORD) . ')' : '');
addSection($sections, "CONFIG", $cfg);

// ---- 5. REQUIRED FILES -------------------------------------------------

$files = [];
$rootDir = realpath(__DIR__ . '/../../..');
$probe = [
    'includes/functions.php',
    'api/system/import_demo_data.php',
    'api/system/db_verify.php',
    'database/demo-data/core.json',
    'system/demo-data/index.php',
];
foreach ($probe as $rel) {
    $full = $rootDir ? $rootDir . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $rel) : null;
    $exists = $full && file_exists($full);
    $files[] = sprintf("%-40s exists=%s readable=%s size=%s",
        $rel,
        $exists ? 'YES' : 'NO ',
        $exists ? bool_str(is_readable($full)) : 'n/a',
        $exists ? safe_size($full) : 'n/a'
    );
}
addSection($sections, "REQUIRED FILES", $files);

// ---- 6. DEMO DATA JSON PARSE ------------------------------------------

$json = [];
$jsonPath = $rootDir . '/database/demo-data/core.json';
if (!file_exists($jsonPath)) {
    $json[] = "FAIL: " . $jsonPath . " does not exist — the import button will fail with 'Demo data file not found'.";
} else {
    $raw = @file_get_contents($jsonPath);
    if ($raw === false) {
        $json[] = "FAIL: could not read file (check filesystem permissions).";
    } else {
        $json[] = "File size      : " . strlen($raw) . " bytes";
        $decoded = json_decode($raw, true);
        if ($decoded === null) {
            $json[] = "FAIL: json_decode error — " . json_last_error_msg();
        } else {
            $json[] = "JSON parse     : OK";
            $json[] = "Top-level keys : " . implode(', ', array_keys($decoded));
            $json[] = "";
            $json[] = "Records per table (across all tiers):";
            $tiers = ['tier1', 'tier2', 'tier3', 'tier4', 'tier5'];
            $totals = [];
            foreach ($tiers as $t) {
                if (!isset($decoded[$t])) continue;
                foreach ($decoded[$t] as $tbl => $rows) {
                    $totals[$tbl] = ($totals[$tbl] ?? 0) + (is_array($rows) ? count($rows) : 0);
                }
            }
            ksort($totals);
            foreach ($totals as $tbl => $n) {
                $json[] = sprintf("  %-25s %d", $tbl, $n);
            }
            $json[] = "";
            $json[] = "Total records to import: " . array_sum($totals);
        }
    }
}
addSection($sections, "DEMO DATA JSON", $json);

// ---- 7. DATABASE CONNECTION -------------------------------------------

$db = [];
$conn = null;
$connOk = false;
$connErr = null;
if (defined('DB_SERVER') && defined('DB_NAME') && defined('DB_USERNAME') && defined('DB_PASSWORD')) {
    try {
        $dsn = "mysql:host=" . DB_SERVER . ";dbname=" . DB_NAME . ";charset=utf8mb4";
        $conn = new PDO($dsn, DB_USERNAME, DB_PASSWORD);
        $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        $connOk = true;
    } catch (Throwable $e) {
        $connErr = $e->getMessage();
    }
} else {
    $connErr = 'DB constants not defined (see CONFIG section)';
}

$db[] = "Connect attempt : " . ($connOk ? 'OK' : 'FAILED');
if (!$connOk) {
    $db[] = "Error           : " . $connErr;
} else {
    try {
        $db[] = "Server version  : " . $conn->getAttribute(PDO::ATTR_SERVER_VERSION);
        $db[] = "Driver          : " . $conn->getAttribute(PDO::ATTR_DRIVER_NAME);
        $row = $conn->query("SELECT DATABASE() AS db, @@character_set_database AS cs, @@collation_database AS coll")->fetch(PDO::FETCH_ASSOC);
        $db[] = "Database        : " . ($row['db'] ?? '');
        $db[] = "Character set   : " . ($row['cs'] ?? '');
        $db[] = "Collation       : " . ($row['coll'] ?? '');
    } catch (Throwable $e) {
        $db[] = "Metadata query failed: " . $e->getMessage();
    }
}
addSection($sections, "DATABASE CONNECTION", $db);

// ---- 8. SCHEMA SANITY (per table) -------------------------------------

$schemaOut = [];
if (!$connOk) {
    $schemaOut[] = "Skipped — no DB connection.";
} else {
    foreach ($EXPECTED_COLUMNS as $table => $expectedCols) {
        $schemaOut[] = "---- {$table} ----";
        // Exists?
        try {
            $exists = (bool)$conn->query("SHOW TABLES LIKE " . $conn->quote($table))->fetchColumn();
        } catch (Throwable $e) {
            $exists = false;
            $schemaOut[] = "  SHOW TABLES failed: " . $e->getMessage();
        }
        $schemaOut[] = "  exists     : " . bool_str($exists);
        if (!$exists) {
            $schemaOut[] = "  > Table missing — run System > Database Verify to create it.";
            $schemaOut[] = "";
            continue;
        }
        // Row count
        try {
            $rc = (int)$conn->query("SELECT COUNT(*) FROM `{$table}`")->fetchColumn();
            $schemaOut[] = "  row count  : " . $rc;
        } catch (Throwable $e) {
            $schemaOut[] = "  row count  : ERROR — " . $e->getMessage();
        }
        // Columns
        try {
            $rows = $conn->query("SHOW COLUMNS FROM `{$table}`")->fetchAll(PDO::FETCH_ASSOC);
            $actualCols = [];
            foreach ($rows as $r) $actualCols[$r['Field']] = $r['Type'] . ($r['Null'] === 'NO' ? ' NOT NULL' : ' NULL');
            $missing = array_diff($expectedCols, array_keys($actualCols));
            $extra   = array_diff(array_keys($actualCols), $expectedCols);
            $schemaOut[] = "  columns    : " . count($actualCols) . " actual / " . count($expectedCols) . " expected";
            if ($missing) {
                $schemaOut[] = "  MISSING    : " . implode(', ', $missing);
            }
            if ($extra) {
                $schemaOut[] = "  extra      : " . implode(', ', $extra) . " (not used by import — usually OK)";
            }
            // Full column list with types
            $schemaOut[] = "  actual columns:";
            foreach ($actualCols as $c => $t) {
                $schemaOut[] = sprintf("    %-30s %s", $c, $t);
            }
        } catch (Throwable $e) {
            $schemaOut[] = "  columns    : ERROR — " . $e->getMessage();
        }
        // Sample first row (redacted)
        try {
            $first = $conn->query("SELECT * FROM `{$table}` ORDER BY 1 LIMIT 1")->fetch(PDO::FETCH_ASSOC);
            if ($first) {
                $first = redact_row($first);
                $schemaOut[] = "  first row  : " . json_encode($first, JSON_UNESCAPED_SLASHES);
            } else {
                $schemaOut[] = "  first row  : (empty)";
            }
        } catch (Throwable $e) {
            $schemaOut[] = "  first row  : ERROR — " . $e->getMessage();
        }
        $schemaOut[] = "";
    }
}
addSection($sections, "SCHEMA SANITY", $schemaOut);

// ---- 9. WRITE PROBE (transactional, rolled back) ----------------------

$probeOut = [];
if (!$connOk) {
    $probeOut[] = "Skipped — no DB connection.";
} else {
    $probeOut[] = "Inserting one sentinel row per writable table inside a transaction,";
    $probeOut[] = "then ROLLBACK so nothing persists. This isolates per-table write errors";
    $probeOut[] = "(FK constraints, NOT NULL violations, charset issues, etc).";
    $probeOut[] = "";
    $token = '_DBG_' . substr(uniqid(), -8);

    // Minimal valid payload per table. Use NULLs/defaults where allowed so we
    // exercise the schema's required columns only. FK-bearing tables get
    // resolved IDs from rows we attempt to insert ahead of them.
    $probePayloads = [
        'analysts'        => ['username' => $token, 'password_hash' => 'x', 'full_name' => $token, 'email' => $token . '@probe.local'],
        'users'           => ['email' => $token . '@probe.local'],
        'departments'     => ['name' => $token],
        'teams'           => ['name' => $token],
        'ticket_types'    => ['name' => $token],
        'ticket_origins'  => ['name' => $token],
        'ticket_prefixes' => ['prefix' => substr($token, -3)],
        // analyst_teams + department_teams need FKs — handled inline after we know IDs
    ];

    try {
        $conn->beginTransaction();
        $insertedIds = [];
        foreach ($probePayloads as $tbl => $payload) {
            try {
                $cols = array_keys($payload);
                $vals = array_values($payload);
                $sql = "INSERT INTO `{$tbl}` (`" . implode('`,`', $cols) . "`) VALUES (" . implode(',', array_fill(0, count($cols), '?')) . ")";
                $stmt = $conn->prepare($sql);
                $stmt->execute($vals);
                $insertedIds[$tbl] = $conn->lastInsertId();
                $probeOut[] = sprintf("  %-18s INSERT OK (new id %s)", $tbl, $insertedIds[$tbl]);
            } catch (Throwable $e) {
                $probeOut[] = sprintf("  %-18s INSERT FAILED — %s", $tbl, $e->getMessage());
            }
        }
        // FK-dependent tables
        if (!empty($insertedIds['analysts']) && !empty($insertedIds['teams'])) {
            try {
                $stmt = $conn->prepare("INSERT INTO analyst_teams (analyst_id, team_id) VALUES (?, ?)");
                $stmt->execute([$insertedIds['analysts'], $insertedIds['teams']]);
                $probeOut[] = "  analyst_teams      INSERT OK";
            } catch (Throwable $e) {
                $probeOut[] = "  analyst_teams      INSERT FAILED — " . $e->getMessage();
            }
        } else {
            $probeOut[] = "  analyst_teams      SKIPPED (analysts or teams probe failed)";
        }
        if (!empty($insertedIds['departments']) && !empty($insertedIds['teams'])) {
            try {
                $stmt = $conn->prepare("INSERT INTO department_teams (department_id, team_id) VALUES (?, ?)");
                $stmt->execute([$insertedIds['departments'], $insertedIds['teams']]);
                $probeOut[] = "  department_teams   INSERT OK";
            } catch (Throwable $e) {
                $probeOut[] = "  department_teams   INSERT FAILED — " . $e->getMessage();
            }
        } else {
            $probeOut[] = "  department_teams   SKIPPED (departments or teams probe failed)";
        }
        $conn->rollBack();
        $probeOut[] = "";
        $probeOut[] = "Transaction rolled back — no probe rows persisted.";
    } catch (Throwable $e) {
        if ($conn->inTransaction()) $conn->rollBack();
        $probeOut[] = "Probe transaction aborted: " . $e->getMessage();
    }
}
addSection($sections, "WRITE PROBE", $probeOut);

// ---- 10. LIVE IMPORT ATTEMPT ------------------------------------------

$liveOut = [];
$importPath = $rootDir . '/api/system/import_demo_data.php';
if (!file_exists($importPath)) {
    $liveOut[] = "Skipped — import script does not exist at: {$importPath}";
} else {
    $liveOut[] = "Calling import_demo_data.php in-process with module=core.";
    $liveOut[] = "If this succeeds, demo core data will be present in the DB after this report.";
    $liveOut[] = "";

    // Custom error handler captures PHP warnings/notices emitted by the import.
    // Severity map deliberately excludes E_STRICT — the constant is deprecated
    // in PHP 8.4+, and referencing it inside the handler would itself emit a
    // DEPRECATED notice that re-entrantly falls through to the default handler.
    //
    // We DO NOT filter known-benign warnings — instead, we keep them visible
    // and annotate each with a plain-English explainer so the reader can tell
    // whether it indicates a real problem or expected noise from running the
    // import inside D001's own request.
    $explainers = [
        'Ignoring session_start'           => "Expected — D001 already started a session, so PHP skipped the import's redundant session_start() call. Not a problem.",
        'session has already been started' => "Expected — same as above, older PHP wording. Not a problem.",
        'headers already sent'             => "Expected — D001 buffers output before sending response headers, so any header() call inside the import is a no-op. Not a problem.",
        'Cannot change session'            => "Expected — the session was already configured by D001, so the import's session call was ignored. Not a problem.",
    ];

    $captured = [];
    set_error_handler(function($severity, $message, $file, $line) use (&$captured, $explainers) {
        $sevMap = [
            E_ERROR             => 'ERROR',
            E_WARNING           => 'WARNING',
            E_PARSE             => 'PARSE',
            E_NOTICE            => 'NOTICE',
            E_CORE_ERROR        => 'CORE_ERROR',
            E_CORE_WARNING      => 'CORE_WARNING',
            E_COMPILE_ERROR     => 'COMPILE_ERROR',
            E_COMPILE_WARNING   => 'COMPILE_WARNING',
            E_USER_ERROR        => 'USER_ERROR',
            E_USER_WARNING      => 'USER_WARNING',
            E_USER_NOTICE       => 'USER_NOTICE',
            E_RECOVERABLE_ERROR => 'RECOVERABLE',
            E_DEPRECATED        => 'DEPRECATED',
            E_USER_DEPRECATED   => 'USER_DEPRECATED',
        ];
        $sevName = $sevMap[$severity] ?? "SEV{$severity}";
        $entry = "[{$sevName}] {$message} in " . basename($file) . ":{$line}";
        foreach ($explainers as $needle => $expl) {
            if (stripos($message, $needle) !== false) {
                $entry .= "\n      -> {$expl}";
                break;
            }
        }
        $captured[] = $entry;
        return true;
    });

    // The import script uses relative includes (require_once '../../config.php')
    // resolved against CWD. Apache sets CWD to the script's directory when serving
    // it directly; we have to replicate that or the require fails. Restore CWD
    // afterwards so nothing else in this request is affected.
    $oldCwd = getcwd();
    @chdir(dirname($importPath));

    $_POST['module'] = 'core';
    $exceptionMsg = null;
    ob_start();
    try {
        include $importPath;
    } catch (Throwable $e) {
        $exceptionMsg = get_class($e) . ': ' . $e->getMessage() . ' at ' . basename($e->getFile()) . ':' . $e->getLine();
    }
    $response = ob_get_clean();

    @chdir($oldCwd);
    restore_error_handler();

    $liveOut[] = "Raw response from import_demo_data.php:";
    $liveOut[] = "  " . (trim($response) === '' ? '(empty)' : $response);
    $liveOut[] = "";

    $parsed = json_decode($response, true);
    if (is_array($parsed)) {
        $liveOut[] = "Parsed result:";
        $liveOut[] = "  success : " . (isset($parsed['success']) ? bool_str($parsed['success']) : '(missing)');
        if (!empty($parsed['error']))    $liveOut[] = "  error   : " . $parsed['error'];
        if (!empty($parsed['module']))   $liveOut[] = "  module  : " . $parsed['module'];
        if (!empty($parsed['total']))    $liveOut[] = "  total   : " . $parsed['total'];
        if (!empty($parsed['imported'])) {
            $liveOut[] = "  imported:";
            foreach ($parsed['imported'] as $tbl => $n) {
                $liveOut[] = sprintf("    %-25s %d", $tbl, $n);
            }
        }
    } else {
        $liveOut[] = "Response was NOT valid JSON — the import script likely fataled or emitted unexpected output.";
    }

    if ($exceptionMsg !== null) {
        $liveOut[] = "";
        $liveOut[] = "Uncaught exception escaped the import:";
        $liveOut[] = "  " . $exceptionMsg;
    }

    if ($captured) {
        $liveOut[] = "";
        $liveOut[] = "PHP errors/warnings emitted during the import:";
        foreach ($captured as $c) $liveOut[] = "  " . $c;
    } else {
        $liveOut[] = "";
        $liveOut[] = "No PHP errors/warnings captured during the import.";
    }

    // Post-import row counts so we can see what actually landed.
    if ($connOk) {
        $liveOut[] = "";
        $liveOut[] = "Post-import row counts:";
        foreach (array_keys($EXPECTED_COLUMNS) as $tbl) {
            try {
                $rc = (int)$conn->query("SELECT COUNT(*) FROM `{$tbl}`")->fetchColumn();
                $liveOut[] = sprintf("  %-25s %d", $tbl, $rc);
            } catch (Throwable $e) {
                $liveOut[] = sprintf("  %-25s ERROR — %s", $tbl, $e->getMessage());
            }
        }
    }
}
addSection($sections, "LIVE IMPORT ATTEMPT", $liveOut);

// ---- 11. FOOTER --------------------------------------------------------

addSection($sections, "END OF REPORT", "Diagnostic {$DIAG_ID} complete. Copy this entire block (from REPORT HEADER above) and send it to support.");

// ---- emit --------------------------------------------------------------

if (!headers_sent()) {
    header('Content-Type: text/plain; charset=utf-8');
    header('Cache-Control: no-store');
}
echo implode("\n\n", $sections) . "\n";
