<?php
/**
 * Debug Tool D002 — Delete Ticket (with full SQL trace)
 *
 * For the support case where deleting a ticket fails with a foreign-key error
 * (typically "1451 Cannot delete or update a parent row" from
 * email_attachments → emails). Enter a ticket reference (ticket_number) and
 * this tool:
 *   1. Resolves the ticket and shows what it found.
 *   2. Audits every table the delete touches — existence, key columns, and the
 *      actual foreign-key constraints + their ON DELETE rule.
 *   3. Counts the child rows that will be removed.
 *   4. Performs the delete inside a transaction, echoing EVERY SQL statement,
 *      its parameters and the affected row count, then COMMITs.
 *   5. Verifies nothing is left behind and removes orphaned attachment files.
 *
 * DESTRUCTIVE: on success the ticket and all its data are permanently deleted.
 *
 * Output: plain text, section-delimited with === HEADERS === for easy skimming.
 */

@session_start();

$DIAG_ID   = 'D002';
$DIAG_NAME = 'Delete Ticket (with full SQL trace)';

// ---- helpers -----------------------------------------------------------

$sections = [];
function addSection(&$sections, $title, $body) {
    if (is_array($body)) $body = implode("\n", $body);
    $sections[] = "=== {$title} ===\n" . rtrim($body, "\n");
}
function bool_str($v) { return $v ? 'YES' : 'NO'; }

function emit_and_exit($sections) {
    if (!headers_sent()) {
        header('Content-Type: text/plain; charset=utf-8');
        header('Cache-Control: no-store');
    }
    echo implode("\n\n", $sections) . "\n";
    exit;
}

// ---- 1. HEADER ---------------------------------------------------------

$ref = trim((string)($_GET['ref'] ?? $_POST['ref'] ?? ''));
$now = gmdate('Y-m-d H:i:s') . ' UTC';
addSection($sections, "REPORT HEADER", [
    "Diagnostic     : {$DIAG_ID} — {$DIAG_NAME}",
    "Generated      : {$now}",
    "Generated by   : analyst_id=" . ($_SESSION['analyst_id'] ?? '(not logged in)'),
    "Ticket ref in  : " . ($ref === '' ? '(none supplied)' : $ref),
    "WARNING        : This tool permanently deletes the ticket and its data.",
]);

// ---- 2. AUTH GATE ------------------------------------------------------

if (!isset($_SESSION['analyst_id'])) {
    addSection($sections, "AUTH", "FAIL: not logged in. Log into Domus Desk in the same browser, then re-run.");
    emit_and_exit($sections);
}

if ($ref === '') {
    addSection($sections, "INPUT", "FAIL: no ticket reference supplied. Type a ticket number (e.g. the value shown as the ticket reference) into the box and click Run.");
    emit_and_exit($sections);
}

// ---- 3. DATABASE CONNECTION -------------------------------------------

$rootCfg = realpath(__DIR__ . '/../../../config.php');
$conn = null; $connErr = null;
try {
    if ($rootCfg) @require_once $rootCfg;
    // Debug tools are administrators-only (issue #34). Fail closed.
    require_once __DIR__ . '/../../../includes/functions.php';
    try { $__dbgAdmin = !empty($_SESSION['analyst_id']) && analystIsAdmin(connectToDatabase(), (int)$_SESSION['analyst_id']); } catch (Throwable $e) { $__dbgAdmin = false; }
    if (!$__dbgAdmin) { http_response_code(403); if (!headers_sent()) header('Content-Type: text/plain; charset=utf-8'); echo "Administrator access required.\n"; exit; }
    if (defined('DB_SERVER') && defined('DB_NAME') && defined('DB_USERNAME') && defined('DB_PASSWORD')) {
        $conn = new PDO(
            "mysql:host=" . DB_SERVER . ";dbname=" . DB_NAME . ";charset=utf8mb4",
            DB_USERNAME, DB_PASSWORD
        );
        $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    } else {
        $connErr = 'DB constants not defined in config.php';
    }
} catch (Throwable $e) {
    $connErr = $e->getMessage();
}

if (!$conn) {
    addSection($sections, "DATABASE CONNECTION", "FAILED: " . ($connErr ?? 'unknown error'));
    emit_and_exit($sections);
}
$dbName = defined('DB_NAME') ? DB_NAME : '';
addSection($sections, "DATABASE CONNECTION", [
    "Connect attempt : OK",
    "Server version  : " . $conn->getAttribute(PDO::ATTR_SERVER_VERSION),
    "Database        : " . $dbName,
]);

// Small introspection helpers bound to this connection.
$tableExists = function($t) use ($conn) {
    try { return (bool)$conn->query("SHOW TABLES LIKE " . $conn->quote($t))->fetchColumn(); }
    catch (Throwable $e) { return false; }
};
$colExists = function($t, $c) use ($conn) {
    try { return (bool)$conn->query("SHOW COLUMNS FROM `{$t}` LIKE " . $conn->quote($c))->fetchColumn(); }
    catch (Throwable $e) { return false; }
};
$count = function($sql, $params) use ($conn) {
    try { $s = $conn->prepare($sql); $s->execute($params); return (int)$s->fetchColumn(); }
    catch (Throwable $e) { return '(error: ' . $e->getMessage() . ')'; }
};

// ---- 4. RESOLVE TICKET -------------------------------------------------

$ticketId = null;
$resolve = [];
try {
    $stmt = $conn->prepare("SELECT id, ticket_number, subject, created_datetime FROM tickets WHERE ticket_number = ?");
    $stmt->execute([$ref]);
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    // Fallback: numeric input may be the raw id.
    if (!$row && ctype_digit($ref)) {
        $stmt = $conn->prepare("SELECT id, ticket_number, subject, created_datetime FROM tickets WHERE id = ?");
        $stmt->execute([(int)$ref]);
        $row = $stmt->fetch(PDO::FETCH_ASSOC);
        if ($row) $resolve[] = "Note: '{$ref}' did not match a ticket_number, but matched ticket id {$ref}.";
    }
    if (!$row) {
        $resolve[] = "FAIL: no ticket found with ticket_number (or id) = '{$ref}'. Nothing deleted.";
        addSection($sections, "RESOLVE TICKET", $resolve);
        emit_and_exit($sections);
    }
    $ticketId = (int)$row['id'];
    $resolve[] = "Matched ticket:";
    $resolve[] = "  id             : " . $row['id'];
    $resolve[] = "  ticket_number  : " . $row['ticket_number'];
    $resolve[] = "  subject        : " . $row['subject'];
    $resolve[] = "  created        : " . $row['created_datetime'];
} catch (Throwable $e) {
    $resolve[] = "FAIL: lookup error — " . $e->getMessage();
    addSection($sections, "RESOLVE TICKET", $resolve);
    emit_and_exit($sections);
}
addSection($sections, "RESOLVE TICKET", $resolve);

// ---- 5. SCHEMA & CONSTRAINT AUDIT -------------------------------------
// Tables the delete touches. "manual" = no cascade, we delete it explicitly;
// "auto" = the FK cascades / sets null when the ticket goes.
$relevant = [
    'email_attachments'   => ['id','email_id','file_path'],
    'emails'              => ['id','ticket_id'],
    'ticket_notes'        => ['id','ticket_id'],
    'ticket_audit'        => ['id','ticket_id'],
    'ticket_time_entries' => ['id','ticket_id'],
    'ticket_recordings'   => ['id','ticket_id'],
    'ticket_csat_responses' => ['id','ticket_id'],
    'ticket_cmdb_objects' => ['id','ticket_id'],
    'sla_notifications_sent' => ['id','ticket_id'],
    'tasks'               => ['id','ticket_id'],
    'tickets'             => ['id','ticket_number'],
];

// Pull every FK in this schema once, keyed by table.
$fksByTable = [];
try {
    $fkStmt = $conn->prepare(
        "SELECT k.TABLE_NAME, k.CONSTRAINT_NAME, k.COLUMN_NAME, k.REFERENCED_TABLE_NAME,
                k.REFERENCED_COLUMN_NAME, r.DELETE_RULE
         FROM information_schema.KEY_COLUMN_USAGE k
         JOIN information_schema.REFERENTIAL_CONSTRAINTS r
           ON r.CONSTRAINT_SCHEMA = k.TABLE_SCHEMA AND r.CONSTRAINT_NAME = k.CONSTRAINT_NAME
         WHERE k.TABLE_SCHEMA = ? AND k.REFERENCED_TABLE_NAME IS NOT NULL"
    );
    $fkStmt->execute([$dbName]);
    foreach ($fkStmt->fetchAll(PDO::FETCH_ASSOC) as $fk) {
        $fksByTable[$fk['TABLE_NAME']][] = $fk;
    }
} catch (Throwable $e) {
    $fksByTable = ['__error__' => $e->getMessage()];
}

$schemaOut = [];
foreach ($relevant as $tbl => $cols) {
    $schemaOut[] = "---- {$tbl} ----";
    if (!$tableExists($tbl)) {
        $schemaOut[] = "  exists     : NO  (skipped during delete)";
        $schemaOut[] = "";
        continue;
    }
    $schemaOut[] = "  exists     : YES";
    $missing = [];
    foreach ($cols as $c) { if (!$colExists($tbl, $c)) $missing[] = $c; }
    $schemaOut[] = "  key columns: " . (empty($missing) ? 'all present (' . implode(', ', $cols) . ')' : 'MISSING ' . implode(', ', $missing));
    // FK constraints declared ON this table (its outgoing references)
    $fks = $fksByTable[$tbl] ?? [];
    if (empty($fks)) {
        $schemaOut[] = "  foreign keys: (none declared)";
    } else {
        $schemaOut[] = "  foreign keys:";
        foreach ($fks as $fk) {
            $schemaOut[] = sprintf("    %s: %s -> %s(%s)  ON DELETE %s",
                $fk['CONSTRAINT_NAME'], $fk['COLUMN_NAME'],
                $fk['REFERENCED_TABLE_NAME'], $fk['REFERENCED_COLUMN_NAME'], $fk['DELETE_RULE']);
        }
    }
    $schemaOut[] = "";
}
if (isset($fksByTable['__error__'])) {
    $schemaOut[] = "NOTE: could not read information_schema FKs — " . $fksByTable['__error__'];
}
addSection($sections, "SCHEMA & CONSTRAINT AUDIT", $schemaOut);

// Sub-select reused below: the email ids belonging to this ticket.
$attEmailSub = "(SELECT id FROM emails WHERE ticket_id = ?)";

// ---- 5b. FOREIGN KEY CHECK & KEY VALUES -------------------------------
// Zero in on the constraint behind the reported "1451" error and dump the
// exact rows/ids involved, so support can see whether THIS ticket would be
// blocked and by which attachments — even if the delete later succeeds.

$fkOut = [];

// (a) The specific FK behind the bug: email_attachments.email_id -> emails.id
$targetFk = null;
foreach (($fksByTable['email_attachments'] ?? []) as $fk) {
    if ($fk['CONSTRAINT_NAME'] === 'fk_email_attachments_email') { $targetFk = $fk; break; }
    if ($fk['REFERENCED_TABLE_NAME'] === 'emails') { $targetFk = $fk; } // fallback: any FK to emails
}
$fkOut[] = "Constraint fk_email_attachments_email (email_attachments.email_id -> emails.id):";
if ($targetFk) {
    $blocks = in_array(strtoupper($targetFk['DELETE_RULE']), ['RESTRICT', 'NO ACTION'], true);
    $fkOut[] = "  present    : YES";
    $fkOut[] = "  name       : " . $targetFk['CONSTRAINT_NAME'];
    $fkOut[] = "  reference  : email_attachments.{$targetFk['COLUMN_NAME']} -> {$targetFk['REFERENCED_TABLE_NAME']}({$targetFk['REFERENCED_COLUMN_NAME']})";
    $fkOut[] = "  ON DELETE  : " . $targetFk['DELETE_RULE'];
    $fkOut[] = "  blocking?  : " . ($blocks
        ? "YES — deleting an email with attachments fails unless the attachments are deleted first. This is the reported bug."
        : "NO — this FK cascades / sets null, so it would not block the delete.");
} else {
    $fkOut[] = "  present    : NO";
    $fkOut[] = "  meaning    : this database has no FK from email_attachments to emails, so the delete cannot fail on it here.";
    $fkOut[] = "               (A fresh install from domus-desk.sql has this FK; installs grown via Database Verify";
    $fkOut[] = "                may not — which is why the bug appears on some installs but not others.)";
}
$fkOut[] = "";

// (b) The other ticket-child FKs the delete also has to respect
$fkOut[] = "Other ticket-child constraints (delete_ticket.php clears these too):";
$otherFks = [
    'ticket_notes'        => 'fk_notes_tickets',
    'ticket_audit'        => 'fk_ticket_audit_ticket',
    'ticket_time_entries' => 'fk_time_entries_tickets',
];
foreach ($otherFks as $tbl => $name) {
    $found = null;
    foreach (($fksByTable[$tbl] ?? []) as $fk) {
        if ($fk['CONSTRAINT_NAME'] === $name || $fk['REFERENCED_TABLE_NAME'] === 'tickets') { $found = $fk; break; }
    }
    $fkOut[] = sprintf("  %-26s %s", $name . ':', $found ? ('present, ON DELETE ' . $found['DELETE_RULE']) : 'absent');
}
$fkOut[] = "";

// (c) The actual ids/values involved — the emails for this ticket...
$fkOut[] = "Emails linked to this ticket (emails.ticket_id = {$ticketId}):";
try {
    $es = $conn->prepare("SELECT id, has_attachments, direction, from_address, subject FROM emails WHERE ticket_id = ? ORDER BY id");
    $es->execute([$ticketId]);
    $emailRows = $es->fetchAll(PDO::FETCH_ASSOC);
    if (!$emailRows) {
        $fkOut[] = "  (none)";
    } else {
        foreach ($emailRows as $er) {
            $fkOut[] = sprintf("  email id %-6s has_attachments=%s direction=%-8s from=%s",
                $er['id'], ($er['has_attachments'] ?? '?'), ($er['direction'] ?? ''), ($er['from_address'] ?? ''));
        }
    }
} catch (Throwable $e) {
    $fkOut[] = "  ERROR reading emails — " . $e->getMessage();
}
$fkOut[] = "";

// ...and the attachments hanging off those emails (the rows that block it)
$fkOut[] = "Attachments on those emails (the rows that trigger the FK error):";
try {
    $as = $conn->prepare(
        "SELECT id, email_id, filename, file_size, file_path
         FROM email_attachments WHERE email_id IN {$attEmailSub} ORDER BY email_id, id"
    );
    $as->execute([$ticketId]);
    $attRows = $as->fetchAll(PDO::FETCH_ASSOC);
    if (!$attRows) {
        $fkOut[] = "  (none — so the foreign key will NOT block this ticket's delete)";
    } else {
        foreach ($attRows as $ar) {
            $fkOut[] = sprintf("  attachment id %-6s email_id=%-6s size=%-9s file=%s",
                $ar['id'], $ar['email_id'], $ar['file_size'], $ar['filename']);
            $fkOut[] = "        path: " . $ar['file_path'];
        }
        $fkOut[] = "";
        $fkOut[] = "  -> These " . count($attRows) . " attachment row(s) must be deleted before their emails row.";
        $fkOut[] = "     That is exactly what Step 1 of the delete below does.";
    }
} catch (Throwable $e) {
    $fkOut[] = "  ERROR reading attachments — " . $e->getMessage();
}
addSection($sections, "FOREIGN KEY CHECK & KEY VALUES", $fkOut);

// ---- 6. PRE-DELETE ROW COUNTS -----------------------------------------

$preOut = [];
$counts = [
    'email_attachments (via emails)' => ["SELECT COUNT(*) FROM email_attachments WHERE email_id IN {$attEmailSub}", [$ticketId]],
    'emails'                         => ["SELECT COUNT(*) FROM emails WHERE ticket_id = ?", [$ticketId]],
    'ticket_notes'                   => ["SELECT COUNT(*) FROM ticket_notes WHERE ticket_id = ?", [$ticketId]],
    'ticket_audit'                   => ["SELECT COUNT(*) FROM ticket_audit WHERE ticket_id = ?", [$ticketId]],
    'ticket_time_entries'            => ["SELECT COUNT(*) FROM ticket_time_entries WHERE ticket_id = ?", [$ticketId]],
    'ticket_recordings (cascade)'    => ["SELECT COUNT(*) FROM ticket_recordings WHERE ticket_id = ?", [$ticketId]],
    'ticket_csat_responses (cascade)'=> ["SELECT COUNT(*) FROM ticket_csat_responses WHERE ticket_id = ?", [$ticketId]],
    'ticket_cmdb_objects (cascade)'  => ["SELECT COUNT(*) FROM ticket_cmdb_objects WHERE ticket_id = ?", [$ticketId]],
    'sla_notifications_sent (cascade)'=> ["SELECT COUNT(*) FROM sla_notifications_sent WHERE ticket_id = ?", [$ticketId]],
    'tasks (set null)'               => ["SELECT COUNT(*) FROM tasks WHERE ticket_id = ?", [$ticketId]],
];
foreach ($counts as $label => [$sql, $params]) {
    $table = strtok($label, ' ');
    if (!$tableExists($table)) { $preOut[] = sprintf("  %-34s (table absent)", $label); continue; }
    $preOut[] = sprintf("  %-34s %s", $label, $count($sql, $params));
}
addSection($sections, "PRE-DELETE ROW COUNTS", $preOut);

// ---- 7. THE DELETE (transactional, every statement logged) ------------

$delOut = [];
$delOut[] = "Running the same FK-safe order as api/tickets/delete_ticket.php,";
$delOut[] = "inside a transaction. Each statement is shown with its parameters";
$delOut[] = "and the number of rows it affected.";
$delOut[] = "";

// Grab attachment file paths before the rows vanish.
$attachmentPaths = [];
try {
    $ps = $conn->prepare("SELECT file_path FROM email_attachments WHERE email_id IN {$attEmailSub}");
    $ps->execute([$ticketId]);
    $attachmentPaths = $ps->fetchAll(PDO::FETCH_COLUMN);
} catch (Throwable $e) {
    $delOut[] = "WARN: could not pre-read attachment paths — " . $e->getMessage();
}

// Ordered list of deletes. Only run those whose table exists.
$steps = [
    ['email_attachments',   "DELETE FROM email_attachments WHERE email_id IN {$attEmailSub}", [$ticketId]],
    ['emails',              "DELETE FROM emails WHERE ticket_id = ?", [$ticketId]],
    ['ticket_notes',        "DELETE FROM ticket_notes WHERE ticket_id = ?", [$ticketId]],
    ['ticket_audit',        "DELETE FROM ticket_audit WHERE ticket_id = ?", [$ticketId]],
    ['ticket_time_entries', "DELETE FROM ticket_time_entries WHERE ticket_id = ?", [$ticketId]],
    ['tickets',             "DELETE FROM tickets WHERE id = ?", [$ticketId]],
];

$deleteOk = false;
try {
    $conn->beginTransaction();
    foreach ($steps as $i => [$tbl, $sql, $params]) {
        $n = $i + 1;
        if (!$tableExists($tbl)) {
            $delOut[] = "Step {$n} [{$tbl}]: SKIPPED — table does not exist.";
            $delOut[] = "";
            continue;
        }
        $delOut[] = "Step {$n} [{$tbl}]:";
        $delOut[] = "  SQL    : " . $sql;
        $delOut[] = "  params : [" . implode(', ', $params) . "]";
        $stmt = $conn->prepare($sql);
        $stmt->execute($params);
        $delOut[] = "  result : OK, rows affected = " . $stmt->rowCount();
        $delOut[] = "";
    }
    $conn->commit();
    $deleteOk = true;
    $delOut[] = "COMMIT — changes are now permanent.";
} catch (Throwable $e) {
    if ($conn->inTransaction()) $conn->rollBack();
    $delOut[] = "";
    $delOut[] = "ERROR during delete — transaction ROLLED BACK, nothing was deleted:";
    $delOut[] = "  " . $e->getMessage();
}
addSection($sections, "DELETE (LIVE)", $delOut);

// ---- 8. POST-DELETE VERIFICATION + FILE CLEANUP -----------------------

$postOut = [];
if (!$deleteOk) {
    $postOut[] = "Skipped — delete did not complete.";
} else {
    $stillThere = $count("SELECT COUNT(*) FROM tickets WHERE id = ?", [$ticketId]);
    $postOut[] = "tickets row for id {$ticketId} remaining: {$stillThere} (expected 0)";
    $orphanAtt = $count("SELECT COUNT(*) FROM email_attachments WHERE email_id IN {$attEmailSub}", [$ticketId]);
    $postOut[] = "email_attachments remaining for ticket  : {$orphanAtt} (expected 0)";
    $postOut[] = "";

    // Remove orphaned attachment files (best effort; never affects the DB result).
    $attachBase = realpath(__DIR__ . '/../../..') . '/tickets/attachments/';
    if (empty($attachmentPaths)) {
        $postOut[] = "Attachment files: none to remove.";
    } else {
        $postOut[] = "Removing " . count($attachmentPaths) . " attachment file(s):";
        foreach ($attachmentPaths as $rel) {
            $full = $attachBase . $rel;
            if (is_file($full)) {
                $postOut[] = "  " . (@unlink($full) ? "deleted  " : "FAILED   ") . $rel;
            } else {
                $postOut[] = "  missing  " . $rel . " (file already gone)";
            }
        }
    }
}
addSection($sections, "POST-DELETE VERIFICATION", $postOut);

// ---- 9. FOOTER ---------------------------------------------------------

addSection($sections, "END OF REPORT",
    "Diagnostic {$DIAG_ID} complete. Copy this entire block (from REPORT HEADER) and send it to support.");

emit_and_exit($sections);
